### ISSUE TITLE
Getting a File not found error

### ISSUE THREAD

**Issue by selinfildis** [tristan/testing.rabbitmq#1]
Hi! 
I keep on getting a file not found error on the runner, I am i missing something? I just changed the rabbitmq_path while initialising. was there a different config i should've done as well? 
```
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/v7/b359vjjn06743ckbrql4935w0000gn/T/tmp9xwi3b6k/runner'
```

Thank you so much!

**Comment by tristan** [comment]
Hi @selinfildis,

Thanks for the report, 
I've just fixed some issues with running this on macOS. Can you update to the 1.0.1 version and try again?

If you still have issues, can you give me some more details about your setup? i.e.
- operating system
- python version
- rabbitmq version
- rabbitmq install method (e.g. brew/apt/compiled from source)

**Comment by selinfildis** [comment]
Thank you, yes it seems to be working now! 
I was on macOS ^^
